#ifndef FILEEXTENSIONS_H
#define FILEEXTENSIONS_H



#define COURSE_UNIT_FILE_EXTENSION ".CourseUnit"
#define SKILL_PACK_FILE_EXTENSION  ".SkillPack"
#define SKILL_FILE_EXTENSION  ".Skill"

#define STUDENT_PROGRESS_FILE_EXTENSION ".StudentProgress"
#define MAIN_COURSEUNIT_FILE_EXTENSION ".CourseInfo"



#endif // FILEEXTENSIONS_H
